#:kivy 1.0.9

<MainWidget>:
    # image: image
    Scatter:
        # Label:
            # font_size: 170
            # center_x: root.width // 2
            # top: root.top // 2
            # text: "000000"

        Image:
            id: image
            # center_x: root.width // 2
            # top: root.height // 2
            pos: 0, 0
            size: root.width, root.height
            texture: root.img_texture

